### ISSUE TITLE
Migrate from SUAVE Rigil testnet to Toliman testnet

### ISSUE THREAD

**Issue by foxytanuki** [mycel-labs/spore#65]
## Description
Due to the closure of the SUAVE Rigil testnet, we need to migrate our application to the Toliman testnet. This migration involves changes to both the frontend and the smart contracts.

## Objectives
1. Update all references to the Rigil testnet in our codebase
2. Redeploy smart contracts to the Toliman testnet
3. Update frontend to interact with the new testnet and contract addresses
4. Ensure all functionality works correctly on the new testnet

### Smart Contracts
- [ ] Review and update smart contract code if necessary for Toliman compatibility
- [ ] Set up deployment scripts for Toliman testnet
- [ ] Deploy all relevant contracts to Toliman testnet
- [ ] Verify contracts on Toliman testnet explorer (if available)
- [ ] Document new contract addresses

### Frontend
- [ ] Update network configuration to point to Toliman testnet
- [ ] Replace all hardcoded Rigil testnet references with Toliman
- [ ] Replace old contract addresses with new Toliman deployed addresses
- [ ] Update any testnet-specific UI elements or messages

### Testing
- [ ] Test all smart contract interactions on Toliman testnet
- [ ] Verify frontend functionality with new testnet
- [ ] Perform end-to-end testing of key user flows

## Additional Considerations
- Ensure sufficient SUAVE tokens are available for testing and contract deployment on Toliman

## Potential Risks
- Toliman testnet may have different characteristics or limitations compared to Rigil
- There might be unforeseen compatibility issues with the new testnet

## Resources
- https://suave-alpha.flashbots.net/toliman

**Comment by taryune** [comment]
https://github.com/flashbots/suave-geth/issues/280
