### ISSUE TITLE
Add default referral code for initial user

### ISSUE THREAD

**Issue by yosui** [mycel-labs/spore#68]
Add default referral code(unlimited invitation) for initial user.

Problem: All users need to get an invitation code from someone, including KOLs, which can be inconvenient when someone want to invite certain people to use the platform. It’s a inconvinient to send both a URL and a referral code.

Solution: Just like how we set the default address to the one used for minting when receiving a previously minted NFT, we could issue an unlimited invitation code provided by the admin as a default referral code."

<img width="616" alt="Screenshot 2024-10-02 at 15 07 17" src="https://github.com/user-attachments/assets/3877292e-392c-49e6-a321-712b4040cce0">

**Comment by foxytanuki** [comment]
duplicate: #61
