### ISSUE TITLE
No new referral code issuance.

### ISSUE THREAD

**Issue by amadison79** [mycel-labs/spore#69]
Referral codes have a limited lifespan, and a renewal occurs when certain milestones are reached in terms of the number of friends invited.

I have noticed that this renewal of new referral codes is no longer working, as well as the increment of the number of invited friends for some time now.

<img width="1470" alt="issue" src="https://github.com/user-attachments/assets/714e952b-f1f8-475d-8a28-3a98b3161044">

**Comment by foxytanuki** [comment]
The issue was resolved by updating our backend API. Thank you for reporting!

**Comment by amadison79** [comment]
With pleasure !
